package com.sajjanmart

import android.app.ActivityManager
import android.app.NotificationManager
import android.content.Context
import android.content.Intent
import android.util.Log
import com.google.firebase.messaging.RemoteMessage
import io.invertase.firebase.common.SharedUtils
import io.invertase.firebase.messaging.ReactNativeFirebaseMessagingReceiver

/**
 * Custom FCM BroadcastReceiver that intercepts NEW_ORDER messages
 * and handles them purely in native Android for background/killed states.
 *
 * Requirements:
 *   - For FCM messages where data.type == "NEW_ORDER":
 *     - If app is backgrounded or completely killed:
 *         1. Handle entirely in native Android.
 *         2. Do NOT depend on React Native JS (never dispatch to super / HeadlessJsTask).
 *         3. Start OrderAlertService passing the complete order data.
 *         4. Create exactly one custom notification (managed by OrderAlertService).
 *         5. Do not allow Firebase to create a duplicate default notification.
 *     - If app is in foreground:
 *         Do not change existing foreground popup behavior (delegate to super for JS modal).
 *   - For all other message types:
 *     Delegate to super for normal library handling.
 */
class CustomMessagingReceiver : ReactNativeFirebaseMessagingReceiver() {

    companion object {
        private const val TAG = "CustomMessagingReceiver"

        /**
         * Suppress any default or duplicate notification generated by Firebase
         * or Google Play Services.
         *
         * Retains ONLY our custom OrderAlertService notification
         * (id = OrderAlertService.NOTIFICATION_ID, tag = null).
         */
        fun suppressDuplicateNotifications(context: Context) {
            try {
                val nm = context.getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
                val activeNotifications = nm.activeNotifications ?: return

                for (sbn in activeNotifications) {
                    val isOurCustomAlert = (sbn.id == OrderAlertService.NOTIFICATION_ID && sbn.tag == null)
                    if (!isOurCustomAlert) {
                        nm.cancel(sbn.tag, sbn.id)
                        Log.d(TAG, "[FCM] Suppressed duplicate/default notification: tag=${sbn.tag} id=${sbn.id} channel=${sbn.notification.channelId}")
                    }
                }
            } catch (e: Exception) {
                Log.e(TAG, "Error suppressing duplicate notification", e)
            }
        }
    }

    override fun onReceive(context: Context, intent: Intent) {
        // Suppress any existing or preemptively posted Firebase default notifications
        suppressDuplicateNotifications(context)

        try {
            val extras = intent.extras
            val remoteMessage = if (extras != null) RemoteMessage(extras) else null
            val data = remoteMessage?.data ?: emptyMap()

            // Helper to get field from data map or bundle extras with fallbacks
            fun getField(vararg keys: String): String? {
                for (key in keys) {
                    val fromData = data[key]
                    if (!fromData.isNullOrBlank()) return fromData
                    val fromExtras = extras?.getString(key)
                    if (!fromExtras.isNullOrBlank()) return fromExtras
                }
                return null
            }

            val type = getField("type", "data.type")

            if (type == "NEW_ORDER") {
                val isForeground = isAppInForeground(context)
                Log.d(TAG, "[FCM] NEW_ORDER received. isForeground=$isForeground")

                if (!isForeground) {
                    // App is backgrounded or completely killed:
                    // Pure native Android handling — NO React Native JS dependency.
                    val orderId = getField("orderId", "order_id", "id") ?: "unknown"
                    val orderNumber = getField("orderNumber", "order_number") ?: orderId
                    val customerName = getField("customerName", "customer_name") ?: ""
                    val customerPhone = getField("customerPhone", "customer_phone") ?: ""
                    val address = getField("address") ?: ""
                    val total = getField("total") ?: ""
                    val paymentMethod = getField("paymentMethod", "payment_method") ?: ""
                    val paymentStatus = getField("paymentStatus", "payment_status") ?: ""
                    val itemsJson = getField("items", "itemsJson", "items_json") ?: "[]"
                    val itemCount = getField("itemCount", "item_count") ?: ""

                    Log.d(TAG, "[FCM] App not in foreground — starting native OrderAlertService")
                    Log.d(TAG, "[ORDER-ALERT] starting for order: $orderId (#$orderNumber)")

                    // Start native OrderAlertService with complete order payload
                    OrderAlertService.start(
                        context = context,
                        orderId = orderId,
                        orderNumber = orderNumber,
                        customerName = customerName,
                        customerPhone = customerPhone,
                        address = address,
                        total = total,
                        paymentMethod = paymentMethod,
                        paymentStatus = paymentStatus,
                        itemsJson = itemsJson,
                        itemCount = itemCount,
                    )

                    // Ensure duplicate Firebase notification is suppressed
                    suppressDuplicateNotifications(context)

                    // CRITICAL: Return immediately!
                    // Do NOT call super.onReceive() in background/killed state for NEW_ORDER.
                    // Calling super would start ReactNativeFirebaseMessagingHeadlessService,
                    // spinning up the JS runtime and running setBackgroundMessageHandler,
                    // which violates "do not depend on React Native JS" and can cause duplicate notifications.
                    return
                } else {
                    Log.d(TAG, "[FCM] App in foreground — delegating to super for JS popup")
                }
            }
        } catch (e: Exception) {
            Log.e(TAG, "Error processing FCM message in CustomMessagingReceiver", e)
        }

        // Delegate to super for:
        // 1. Foreground NEW_ORDER (fires onMessage in JS for in-app popup modal)
        // 2. All other message types, token refreshes, etc.
        super.onReceive(context, intent)
    }

    /**
     * Check if the app is in the foreground.
     * Uses SharedUtils.isAppInForeground from @react-native-firebase with
     * fallback to ActivityManager process importance check.
     */
    private fun isAppInForeground(context: Context): Boolean {
        try {
            if (SharedUtils.isAppInForeground(context)) {
                return true
            }
        } catch (e: Exception) {
            Log.w(TAG, "SharedUtils foreground check failed, falling back to ActivityManager", e)
        }

        try {
            val am = context.getSystemService(Context.ACTIVITY_SERVICE) as? ActivityManager
            val procs = am?.runningAppProcesses ?: return false
            for (proc in procs) {
                if (proc.processName == context.packageName) {
                    return proc.importance == ActivityManager.RunningAppProcessInfo.IMPORTANCE_FOREGROUND
                }
            }
        } catch (e: Exception) {
            Log.e(TAG, "Error checking ActivityManager foreground state", e)
        }
        return false
    }
}

